### ISSUE TITLE
Switch remaining resources to HTTPS and enable new force_https option

### ISSUE THREAD

**Issue by edmorley** [mozilla/moz-corsica#109]
The upstream mozilla/corsica#52 PR has now merged.

Next steps are:
* updating state.json to use all HTTPS links
* getting a new upstream mozilla/corsica release pushed to NPM
* deploying that release on the Mozilla instance, with the `force_https` option set to `true`

**Comment by StevenZhang123** [comment]
I would like to do this.

**Comment by luciusbono** [comment]
We're extremely interested in doing this, as it's potentially blocking us here: https://github.com/mozilla/dinobuildr/pull/107

Context: we're building a macOS deployment for use in Mozilla offices that will automatically configure Corsica displays. 

Anything blocking the switch to HTTPS? @tristanthomas did some limited testing and it seems that only the following sites are incompatible with HTTPS:

http://micropipes.com/temp/
http://emanueladamiani.com/photon/welcome-june.jpg

**Comment by mythmon** [comment]
All links are HTTPS now.
