### ISSUE TITLE
Weighting/prioritization for tags

### ISSUE THREAD

**Issue by lmandel** [mozilla/moz-corsica#18]
Tags are great. However there is certain content (say release related information) that I think should be displayed more frequently on the boards than fun content (say whimsy - I know, blasphemy!). It would be nice to be able to weight/prioritize the content somehow.

**Comment by mythmon** [comment]
We've talked about this feature in the main corsica repo before: https://github.com/mozilla/corsica/issues/22

**Comment by lmandel** [comment]
Thanks for the pointer. I'm going to close this issue in favour of the one filed in the main Corsica repo.
