### ISSUE TITLE
TPE Coursica Content 

### ISSUE THREAD

**Issue by niyali** [mozilla/moz-corsica#182]
the name of the screen: mammomax
where it's physically located: Taipei office 
what content should be on it: https://drive.google.com/open?id=1KDY7z6Pe6sW_aqHXWCJkPokDJ4Ld8jL2
any other special requests: need to replay the video repeatedly

Thank you very much.

**Comment by mythmon** [comment]
Hello Niyali,

I tried to set this up on a local Corsica instance for testing, and I'm having trouble getting the video to autoplay from Google Drive. Would it be possible to upload this video to Youtube? We have some support for that should make it easier to set up this integration.

**Comment by niyali** [comment]
Hello Michael,

Thank you for your prompt reply. 
Here are the materials with YouTube links. 

Very much appreciate your help. 
Thank you. 

Video:
https://www.youtube.com/watch?v=f9SGl_5D1hk
https://www.youtube.com/watch?v=5XJC9LOl6Us
https://www.youtube.com/watch?v=RrYrFpoUXiQ&t=120s
https://www.youtube.com/watch?v=ydQbAGLDZ-k

google slide
https://docs.google.com/presentation/d/1gGZ3Mzl9LbiN-sT8XB9Ip7Kq5XZQ2plGZPSJsAfm8b8/edit?usp=sharing

**Comment by mythmon** [comment]
I've set up a tag with the Youtube videos and Google Slides deck. One thing to note is that the Corsica system does not support time offsets for videos currently. I added your third video in a way that will start at the beginning. If you'd prefer, I can remove it entirely instead.

Additionally, as I tried to set up the screen, I don't see any screen online named "mammomax". For the final set up, it needs to be online. Alternatively you can use [the Corsica repl](https://github.com/potch/corsica-repl) to run the following two commands

```
admin type=subscribe screen=mammomax tag=tpe-comms
admin type=rename screen=mammomax name=tpe-ambient-1
```

Feel free to use a different name than "tpe-ambient-1".

**Comment by niyali** [comment]
Hello Michael,

So I've get it rename to "tpe-ambient-1" and refresh the page but I don't see the contents pushed to it.

Anything I missed?

FWIW, it's connecting to SSID Mozilla Guest.

Thank you very much.

**Comment by niyali** [comment]
fyi - I got it connected to office wired network and have it online.  
![Screen Shot 2019-12-19 at 3 16 07 PM](https://user-images.githubusercontent.com/1436482/71152846-8454fd80-2272-11ea-84ec-55cc609abfa3.png)

**Comment by niyali** [comment]
Yes it works!

Thank you so much for your prompt response!
Appreciated!

**Comment by niyali** [comment]
Hello Michael, 

The Videos seemed play just fine, but the gslide didn't. 

https://drive.google.com/file/d/12qYuyMsSCK_OOAyn91OVQDXo0nMAqQFH/view?usp=sharing
When it started to play gslide, it'll stop at one random slide(there are 31 slides in total) then started to play another video link. 

Is it normal?

**Comment by mythmon** [comment]
Yes, this is the expected behavior for gslides. The Corsica/gslides integration was made to provide a large group of content that is easy to organize. It was not intended to show a presentation as an animation.

We could explore expanding the gslide integration to support showing all slides in a deck. That's controlled by the code in this repo: https://github.com/mythmon/corsica-google-presentation

**Comment by lonnen** [comment]
I believe this issue is moot now
