### ISSUE TITLE
Transit dashboards for SF

### ISSUE THREAD

**Issue by lonnen** [mozilla/moz-corsica#21]
Info from Nextbus.com on approaching Muni light rail trains for the KT-Ingleside/Third St. and N-Judah lines   (both directions)    at the Embarcadero & Fulsom light rail stop outside the office.

I'm sure there are some bus routes important to SFO's mozillians, but I don't know what they are.

Upcoming Caltrain departures from 4th & King.

Highway travel times from here to:  Mt. View,  Oakland,  Berkeley, San Leandro, Walnut Creek, Concord and Richmond.

Plug in request from Richard

**Comment by mythmon** [comment]
Cleaning up old issues.
