### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [mozilla/moz-corsica#28]
This repo is public, but it's not easy to find out how I'm allowed to use or share the code. Could you add a LICENSE file to make it easier for users to understand how you'd like it to be used?

http://choosealicense.com/ might be helpful here.

Thanks!

**Comment by mitaa** [comment]
When using the MPL you need to put the appropriate header at the top of each file covered by the license. (point 1.4 in the License text)

**Comment by lonnen** [comment]
Incorrect, but thank you for the suggestion. 

https://www.mozilla.org/MPL/2.0/FAQ.html#header-locations

It is common practice to use a LICENSE file instead of headers in MPL2 Mozilla projects intended to run on the server.
