### ISSUE TITLE
Please document a way to deploy moz-corsica on system without dev console access

### ISSUE THREAD

**Issue by sylvestre** [mozilla/moz-corsica#35]
In the Paris office, we have a Panasonic tv and it does not seem easy to get access to the developer console.

It would be great to have a way to set up moz-corsica with a few lines of code and just publish it online.

**Comment by sylvestre** [comment]
Or passing the tags in the URL would be enough.

**Comment by miketaylr** [comment]
@sylvestre have you opened a bug against the FxOS TV? Not being able to connect devtools seems like a big problem.

**Comment by potch** [comment]
These docs live at https://github.com/potch/corsica-repl#setup
