### ISSUE TITLE
Running corsica locally modifies state.json

### ISSUE THREAD

**Issue by catlee** [mozilla/moz-corsica#59]
If I run the local node server, state.json ends up being modified locally. It looks like it's been re-indented from 2-space indentation to 4-space indentation.

**Comment by mythmon** [comment]
`state.json` is used as a writable data store, for storing settings that might change during runtime. It is probably a bug that we wrote the file without any changes being made, but locally modifying is a feature, not a bug.

**Comment by catlee** [comment]
Ok. It just makes submitting changes to it awkward.

1) Update state.json with new data
2) Commit / stash copy somewhere
2) Run node to verify
3) Revert changes to state.json
4) Go back to step 1, or push if you're happy

**Comment by mythmon** [comment]
That makes sense. I think making sure that nothing gets written if the data doesn't change will resolve this issue, and will generally be a good idea. It also sounds like we might want to auto-detect indentation, instead of always assuming 2 space tabs.

**Comment by edmorley** [comment]
Or even if we don't auto-detect indentation, we could one-off fix state.json now to whatever indentation the output uses.

**Comment by mythmon** [comment]
Cleaning up old issues.
