### ISSUE TITLE
New clients in Taipei

### ISSUE THREAD

**Issue by timdream** [mozilla/moz-corsica#78]
* the name of the screen: `whitman-debra`, `feron`, please it rename it to something sane.
* where it's physically located: 4F & 5F TPE seating area but not pointing to any seats -- feel free to configure animation on.
* what content should be on it: `ambient`, `platform`. I am not sure about other content.
* any other special requests: maybe teach us how to get a `tpe` channel? I am interested in putting something like weather on it...

**Comment by lonnen** [comment]
I'm sorry this took a while. I created an empty `tpe` channel, first. To add content, either file issues with URLs or open pull requests adding them to this array: https://github.com/mozilla/moz-corsica/blob/master/state.json#L136

Then I renamed `feron` to `tpe-commons2` and subscribed it to `ambient`, `platform`, and 'tpe'.

I do not see any screens named `whitman-debra`. I do see a `leeds-betty-brant`. Could you refresh the page and confirm the name?

**Comment by timdream** [comment]
Oh I didn't know I have to leave the it on. We are on holiday and will be back on Mar 1st.

**Comment by lonnen** [comment]
It's ok. Go enjoy your holiday!

The machines will save their information, but I cannot set it remotely unless it is connected to the server.

**Comment by timdream** [comment]
I've just turn the machine on. So if there are new machines coming up online (and I have DevTools access), is there any difference between pushing configure remotely by you or me `writeConfig()` myself? If there isn't for future devices I can just configure myself.

**Comment by lonnen** [comment]
There is no difference. I'm remotely configuration

**Comment by timdream** [comment]
Thanks for the help. Let me close this one out then.
